# Generated by Django 3.1.2 on 2020-10-22 04:31

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        superuser = User.objects.create_superuser(
            username=settings.DJANGO_SU_NAME,
            password=settings.DJANGO_SU_PASSWORD)

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
